### ISSUE TITLE
生成bin文件生成不出来不知道什么问题

### ISSUE THREAD

**Issue by MaxSecurity** [Twi1ight/CSAgent#11]

**Comment by MaxSecurity** [comment]
用自带的exe可以生成

**Comment by DroidKali** [comment]
实测可以生成没问题

**Comment by MaxSecurity** [comment]
> 实测可以生成没问题
奇怪了我再我本机可以做的虚拟机不行

**Comment by MaxSecurity** [comment]
![image](https://user-images.githubusercontent.com/16812469/140363507-28d29439-97d1-43a2-b665-c8e4f12fcbd4.png)
生成bin文件报错

> 实测可以生成没问题

**Comment by Twi1ight** [comment]
你用的不是4.4原版，是别人发的破解版吧
