### ISSUE TITLE
cs4.4使用https生成exe问题

### ISSUE THREAD

**Issue by moyuwa** [Twi1ight/CSAgent#12]
VM虚拟机内网环境，无任何防护无杀软，防火墙全关，kali2021运行cs4.4使用https生成exe，在win10x64上运行可上线，win7x64运行无法上线（使用http都可上线），请问这个问题遇到过吗？

**Comment by yangyang1144** [comment]
这个应该就是你自己的问题了  我用的这个版本没有任何问题

**Comment by Twi1ight** [comment]
> VM虚拟机内网环境，无任何防护无杀软，防火墙全关，kali2021运行cs4.4使用https生成exe，在win10x64上运行可上线，win7x64运行无法上线（使用http都可上线），请问这个问题遇到过吗？

没碰到过，你win7是新装的虚拟机吗？win7镜像内置的根证书已经过期了，我记得很之前装机器的时候访问很多https网站都会出问题，不知道有没有关系
