### ISSUE TITLE
CS 4.5 来了！

### ISSUE THREAD

**Issue by Asura88** [Twi1ight/CSAgent#14]
圣诞节快乐！

CS 4.5 来了！

后门自测！

https://gofile.io/d/CNrMjr
https://ufile.io/c8s2focy
https://anonfiles.com/t8PfD3T5w6/cobaltstrike_jar

**Comment by DroidKali** [comment]
不是原版的包吧，还是坐等原版的包

**Comment by badboycxcc** [comment]
和原版hash对不上呀
