### ISSUE TITLE
cs4.3 error

### ISSUE THREAD

**Issue by websecer** [Twi1ight/CSAgent#15]
`java -XX:ParallelGCThreads=4 -XX:+AggressiveHeap -XX:+UseParallelGC -javaagent:CSAgent.jar=3a4425490f389aeec312bdd758ad2b99 -jar cobaltstrike.jar
[!] Trapped java.io.EOFException during client (192.168.0.109) read [TeamQueue Reader]: null
[-] Trapped java.lang.NullPointerException during team reader [TeamQueue Reader]: null
java.lang.NullPointerException
	at common.TeamQueue.processRead(Unknown Source)
	at common.TeamQueue$TeamReader.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by Twi1ight** [comment]
请提供详细情况说明，是否使用原版jar，Java版本，操作系统类型，就贴这么个错误信息没有任何用处

**Comment by yanghaoi** [comment]
Hello,this error is  when you use agscript in linux (no gui).Just add a parameter   `-Djava.awt.headless=true ` in your command line:

`java -XX:ParallelGCThreads=4 -XX:+AggressiveHeap -XX:+UseParallelGC -Djava.awt.headless=true -classpath ./cobaltstrike.jar aggressor.headless.Start $*`

Link: 
[](https://stackoverflow.com/questions/10165761/java-cant-connect-to-x11-window-server-using-localhost10-0-as-the-value-of-t)

[](https://www.oracle.com/technical-resources/articles/javase/headless.html)
