### ISSUE TITLE
kali2021-jdk11-0-11使用报错

### ISSUE THREAD

**Issue by Look4your** [Twi1ight/CSAgent#17]
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Error: Could not find or load main class server.TeamServer
Caused by: java.lang.ClassNotFoundException: server.TeamServer
有没有大佬知道如何解决

**Comment by Baikeryoyo** [comment]
不行你换个Java版本呢，Java是可以多版本共存的

**Comment by Look4your** [comment]
> 不行你换个Java版本呢，Java是可以多版本共存
上面的报错解决了。启动服务之后没有服务弹窗。大佬有遇到过吗？
OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[*] Loading properties file (/root/CSAgent/TeamServer.prop).
[!] Properties file (/root/CSAgent/TeamServer.prop) was not found.
[+] Team server is up on 0.0.0.0:50050
[*] SHA256 hash of SSL cert is: e1d352cd9e3ea8fa58a8741408252ddbd492c9b3d51a86747355207cb29ce149

到这里就没任何反应了

**Comment by admin-set** [comment]
Error: Could not find or load main class server.TeamServer
Caused by: java.lang.ClassNotFoundException: server.TeamServe

**Comment by admin-set** [comment]
Error: Could not find or load main class server.TeamServer
Caused by: java.lang.ClassNotFoundException: server.TeamServe
大佬知道这是啥原因不

**Comment by Baikeryoyo** [comment]
> 报错：Could not find or load main class server.TeamServer Caused by: java.lang.ClassNotFoundException: server.TeamServe 大佬这是啥原因不知道

一样，是版本问题

**Comment by admin-set** [comment]
我在GitHub不是删掉 了评论吗，为啥还看得到，已经使用java 8、16、17 进行安装，都是这样的问题，现在在尝试java13

**Comment by admin-set** [comment]
java 13 也还是这样的问题

**Comment by Baikeryoyo** [comment]
> 

只用8和15测试就好了，是可以双版本存在的，另外你确定你重新安装后的环境变量设置对了嘛

**Comment by admin-set** [comment]
环境变量是没有问题的，因为我测试一个删除一次java，我现在尝试一下15

**Comment by Baikeryoyo** [comment]
> 环境变量是没有问题的，因为我测试一个删除一次java，我现在尝试一下15

不用那么麻烦，两个都安装，然后在环境变量里面添加两个路径，需要用哪个版本就把哪个路径上移，或者你运行的时候手动指定路径都可以的比如
“C:/JAVA15/BIN/java.exe” -jar 文件名

**Comment by Baikeryoyo** [comment]
> > 个麻烦，两
> 
> 我是在linux服务器下进行安装的，其实也不麻烦

Linux也是一样的，可以双版本，你搜索一下呢

**Comment by Baikeryoyo** [comment]
> root@VM-16-14-ubuntu:~# java -version openjdk version "1.8.0_312" OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07) OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
> 
> root@VM-16-14-ubuntu:~/cs_loader4.5# ./teamserver ip 123456qwert [*] Will use existing X509 certificate and keystore (for SSL) Error: Could not find or load main class server.TeamServer

你给权限了嘛？

**Comment by admin-set** [comment]
TeamServer的权限是777，cs文件夹权限也是777，但是还是运行失败

[*] Will use existing X509 certificate and keystore (for SSL)
Error: Could not find or load main class server.TeamServer
root@VM-16-14-ubuntu:~/cs_loader4.5# ll

**Comment by Twi1ight** [comment]
> > 不行你换个Java版本呢，Java是可以多版本共存
> > 上面的报错解决了。启动服务之后没有服务弹窗。大佬有遇到过吗？
> > OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
> > [_] Loading properties file (/root/CSAgent/TeamServer.prop).
> > [!] Properties file (/root/CSAgent/TeamServer.prop) was not found.
> > [+] Team server is up on 0.0.0.0:50050
> > [_] SHA256 hash of SSL cert is: e1d352cd9e3ea8fa58a8741408252ddbd492c9b3d51a86747355207cb29ce149
> 
> 到这里就没任何反应了

这个就是teamserver运行成功了啊
我理解你说的弹窗是要运行客户端才有的吧？
