### ISSUE TITLE
Cobalt Strike 4.5自定义生成store格式的证书运行报错

### ISSUE THREAD

**Issue by BambooLove** [Twi1ight/CSAgent#25]
采用默认证书可以正常进行运行，自定义生成证书无法运行。
![image](https://user-images.githubusercontent.com/58097248/173192114-748e53d1-a687-463e-984a-ada69ca60063.png)
![image](https://user-images.githubusercontent.com/58097248/173192150-2fd1bd76-bc82-4eb2-86d0-8d64bc4badd4.png)

证书生成命令如下：
`keytool -keystore cobaltstrike.store -storepass 123456 -keypass 123456 -genkey -keyalg RSA -alias baidu.com -dname "CN=ZhongGuo, OU=HAHA, O=HAHAC, L=TaiYuan, ST= ShanXi, C=CN"`

`keytool -importkeystore -srckeystore cobaltstrike.store -destkeystore cobaltstrike.store -deststoretype pkcs12`

生成证书的java版本如下：
![image](https://user-images.githubusercontent.com/58097248/173192264-a7eb2143-8397-4163-9274-6fd074f0d4e1.png)

本人比较菜，最后希望师傅有时间可以帮忙看下怎么解决，感谢~

**Comment by Twi1ight** [comment]
仔细看看报错信息
![image](https://user-images.githubusercontent.com/7844543/173192774-b1f88aa4-5e12-4db5-89b2-83e8ae00aeec.png)

**Comment by BambooLove** [comment]
已解决，谢谢。
