### ISSUE TITLE
这一步如何操作？“”替换cobaltstrike、teamserver、agscript、c2lint、cobaltstrike.bat文件中的解密key“”

### ISSUE THREAD

**Issue by little-trifler** [Twi1ight/CSAgent#26]
这一步如何操作？“”替换cobaltstrike、teamserver、agscript、c2lint、cobaltstrike.bat文件中的解密key“”

**Comment by Pernat1y** [comment]
Open files in notepad -> replace the strings

**Comment by little-trifler** [comment]
> Open files in notepad -> replace the strings

thank you !

**Comment by Twi1ight** [comment]
现在的发布版本里是已经替换好的4.5版本
