### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by tin7safe** [Twi1ight/CSAgent#3]
版本4.3。原版是没问题的。加载器在jdk16下无法使用。
![image](https://user-images.githubusercontent.com/22520854/132092766-f4b2db62-d61e-4196-b481-3d69b67a4102.png)

**Comment by Twi1ight** [comment]
你是github上下的版本还是之前在t00ls上下载的？

**Comment by tin7safe** [comment]
ddosi.com 应该是那下的4.3。如果用你发的那个版本就没问题。
