### ISSUE TITLE
服务端启动报错

### ISSUE THREAD

**Issue by bingling123** [Twi1ight/CSAgent#31]
![image](https://user-images.githubusercontent.com/48980951/174538112-8871db62-6a54-4391-93d1-b461c677edfa.png)
运行报错，使用提示的命令迁移格式默认密码123456错误

**Comment by Twi1ight** [comment]
我把teamserver里面的密码改成了Microsoft，不是123456

**Comment by Twi1ight** [comment]
另外还报错说没有server.TeamServer，你应该是没有下载正版的cobaltstrike.jar
