### ISSUE TITLE
cs4.5 启动界面空白

### ISSUE THREAD

**Issue by depycode** [Twi1ight/CSAgent#33]
请问运行cobaltstrike.bat 后界面是空白的是什么原因？
版本：cs4.5 下载地址：https://wwb.lanzouf[.]com/iImtE0741nub
![image](https://user-images.githubusercontent.com/13741236/176465937-9b75c856-9acf-459a-9452-e95d301f9fe5.png)

**Comment by Twi1ight** [comment]
Windows出现这个有可能是java版本问题，命令行窗口有报错么？

**Comment by depycode** [comment]
jdk 1.8.0_221、jdk10、jdk11 都测试过，运行10多次有一次成功显示出界面，其余均是空白界面。

命令行窗口无报错，看似界面空白实际上应该已加载出来只是显示问题，点击空白处会跳转到 Cobalt Strike 官网。

**Comment by Asura88** [comment]
java -Dfile.encoding=UTF-8 -XX:ParallelGCThreads=4 -XX:+AggressiveHeap -XX:+UseParallelGC -javaagent:CSAgent.jar=CSAgent.properties -Duser.language=en -jar cobaltstrike.jar %*

**Comment by Asura88** [comment]
你把设置的内存删了试试

**Comment by depycode** [comment]
运行报出内存不足才加的设置内存。在虚拟机里面正常运行，有点奇怪。

**Comment by jhhd88** [comment]
我的也经常这样，后来我发现连续开两个，第二个就会正常显示，再把第一个关了就是了
