### ISSUE TITLE
計算的水印哈希不正確

### ISSUE THREAD

**Issue by noobib** [Twi1ight/CSAgent#34]
計算的水印哈希不正確。例如嘗試 700000000。

**Comment by Twi1ight** [comment]
Python写的没有考虑乘法溢出，晚点我修一下

**Comment by noobib** [comment]
我在 Beacon 內部跟踪它，密鑰的計算方式完全不同。我用Java實現了計算，但是Java也沒有溢出能力。我通過計算 & 0xffffffff 使用了人工“溢出”。

**Comment by Twi1ight** [comment]
700000000我计算是对的，不过确实存在另外的问题，目前已经修复了
