### ISSUE TITLE
关于CSAgent使用问题

### ISSUE THREAD

**Issue by CNMBworld** [Twi1ight/CSAgent#4]
请问可以出一个使用教程吗？新手小白的我操作到第二步就不会了

**Comment by Twi1ight** [comment]
你是不知道怎么获取解密key还是其他问题？
如果用4.3原版直接加载起来就行，不用改key

**Comment by Twi1ight** [comment]
需要解密对应版本官方签发的cobaltstrike.auth文件，解密代码可以看cobaltrike.jar里面的common.AuthCrypto类的decrypt方法，在common.Authorization中有调用

以下是各个版本的官方加密key：
4.0    1be5be52c6255c33558e8a1cb667cb06
4.1    80e32a742060b884419ba0c171c9aa76
4.2    b20d487addd4713418f2d5a3ae02a7a0
4.3    3a4425490f389aeec312bdd758ad2b99

**Comment by ybdt** [comment]
谢师傅~

**Comment by CNMBworld** [comment]
我是不知道替换文件到哪里，替换到插件和替换到原文件夹都不能

**Comment by Twi1ight** [comment]
> 我是不知道替换文件到哪里，替换到插件和替换到原文件夹都不能

替换cobaltstrike、teamserver、agscript、c2lint、cobaltstrike.bat文件中的解密key，目前内置的key是4.3版本的
就是把这几个文件中的3a4425490f389aeec312bdd758ad2b99换成你要的对应版本的key

**Comment by CNMBworld** [comment]
文件不需要替换吗？如果可以，录个视频或者动图指导下我这种小白呗
