### ISSUE TITLE
跨目录失效汉化问题 

### ISSUE THREAD

**Issue by And-U** [Twi1ight/CSAgent#6]
只在Mac OS和Win下进行了测试 
CSAgent执行的时候如果涉及到了跨目录 汉化失效 白嫖破解功能还是可以用的
使用命令
java -XX:ParallelGCThreads=4 -XX:+AggressiveHeap -XX:+UseParallelGC -Xdock:icon="../Resources/macIcon.icns" -Xdock:name="Cobalt Strike 4.4"  -javaagent:../Java/CSAgent.jar=5e98194a01c6b48fa582a6a9fcbb92d6 -Duser.language=cn -jar ../Java/cobaltstrike.jar
在Java目录下为汉化版
在其他同级目录则白嫖功能成功 汉化失败

**Comment by And-U** [comment]
不 咱们俩可能理解的不太一样。我说的是命令行  而不是文件 
![image](https://user-images.githubusercontent.com/45547668/137606919-90e1aa54-0b01-46a7-b052-01a9c1531747.png)
![image](https://user-images.githubusercontent.com/45547668/137606921-fb8a6b61-3b2d-42fd-85e9-2c4624e73ede.png)

**Comment by Twi1ight** [comment]
工作目录的问题，必须在csagent.jar和cobaltstrike.jar所在目录运行，这两个东西取资源都是走的相对目录，你不在他们所在的目录运行取不到资源

**Comment by DroidKali** [comment]
下个版本会更改资源获取方式吗？我这边尝试用jpackage打包macapp也是能用白嫖功能但是汉化失败

**Comment by Twi1ight** [comment]
就算改了Agent也没有意义，CS本身的资源获取方式还是从相对目录读取，除非你自己加代码hook cs读取资源方式，这个功能点并不是强需求，后续版本不会添加这个功能

**Comment by DroidKali** [comment]
好吧，感谢大佬

**Comment by DroidKali** [comment]
我尝试解包把resources和scripts里面的翻译文件替换进CS原版包里能实现部分功能汉化了，暂时就这样将就着用吧

**Comment by Twi1ight** [comment]
你这样会有问题的，你修改了jar包，会触发暗桩，上线30分钟后执行任意命令会掉线

**Comment by DroidKali** [comment]
啊这，忘了有暗桩了😥，那我还是用命令启动吧
